# ===============================
# = DATA SOURCE / JPA / HIBERNATE
# ===============================

spring:
  application:
    name: YouTap Microservice

# ===============================
# = APPLICATION / ERROR HANDLING
# ===============================

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

info:
  app:
    name: YouTap Microservice
    description: YouTap Microservice
    version: 1.0
    basePackage: zw.dreamhub
  contact:
    name: Marlvin Chihota
    url: https://www.marlvinzw.me
    email: hello@marlvinzw.me

# ===============================
# = ACTUATOR
# ===============================
management:
  endpoint:
    auditevents:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      group:
        app:
          show-components: always
          show-details: always
          include:
            - ping
            - readinessProbe
            - info
      show-details: always

    # ==========================================
    # APP
    # ==========================================

app:
  userService:
    url: https://jsonplaceholder.typicode.com/users

    # ==========================================
    # SPRING DOC
    # ==========================================

springdoc:
  show-actuator: false
